### PR TITLE
Windows/Hyper-V note in README.md (oracle#285)

### LINKED ISSUE #285: Top level README suggestion - Windows/Hyper-V
There have been a few issues (#267, #240, #222, #216) with these projects related to Hyper-V on Windows hosts. Would it be helpful to add a note in the "Known issues" section of the top level README about this?  Perhaps something like:

### Hyper-V on Windows hosts

The projects in this repository are unlikely to work correctly on Windows hosts with Hyper-V enabled.

Windows features that enable Hyper-V include Application Guard, Containers, Credential Guard, Device Guard, Hyper-V, Virtual Machine Platform, Windows Hypervisor Platform, Windows Sandbox, and Windows Subsystem for Linux (WSL2 only; WSL1 does _not_ use Hyper-V). If you encounter problems with the projects on a Windows host, please try disabling these features.

### PR DESCRIPTION
**Pull request by PaulNeumann**
Add note to top-level `README.md` stating that the projects in this repository are unlikely to work correctly on Windows hosts with Hyper-V enabled.

Closes #285.

Signed-off-by: Paul Neumann <38871902+PaulNeumann@users.noreply.github.com>

### CODE REVIEW

**Review by totalamateurhour — DISMISSED** [review]
LGTM

**Comment by AmedeeBulle** [comment]
Shouldn't we mention the magic incantation (`bcedit ...` / reboot) as it seems that simply disabling Hyper-V from the UI is not always enough?

(I can be wrong here, I have no experience with Windows)

**Comment by PaulNeumann** [comment]
@AmedeeBulle I'm happy to do that. You're right; running `bcdedit` is often required to completely disable Hyper-V. Would the following addition work?

To completely disable all Hyper-V features, it may be necessary to run the command `bcdedit /set hypervisorlaunchtype Off` from an Administrator Command Prompt. After running this command, reboot the computer.

**Comment by AmedeeBulle** [comment]
Thanks @PaulNeumann  It definitely works for me.

@totalamateurhour, what do you think?

**Comment by totalamateurhour** [comment]
Yes, works for me too.

**Comment by PaulNeumann** [comment]
@AmedeeBulle @totalamateurhour Thanks for your feedback! I've updated the PR as suggested. Please let me know if you'd like any additional changes.

**Review by gvenzl — APPROVED** [review]

**Pull request merged**
