### PR TITLE
59 vagrant box for golden gate

### PR DESCRIPTION
**Pull request by ninadingole**
This PR request introduces oracle golden gate + Oracle database 12c on vagrant.
This will help all the devs working on CDC event processing application to have there own dev environment on any machine have vagrant.
I am currently working with a client where this was a requirement and team was missing this setup on MAC machines. So, I have added a new folder in the repo to have Oracle Golden Gate along with Kafka (confluent).

use `vagrant up` as usual to provision the box. After installation is done you will see golden gate & golden gate for big data installed in `/u01/ogg/` and `/u01/oggbd` folder.

Kafka is also installed with java version8 running on port 2181, 9092.

Signed-off-by: Neenad Ingole <ninad.ingole@gmail.com>

### CODE REVIEW

**Comment by javatarz** [comment]
@gvenzl, @scoter-oracle: Have either of you had a chance to look into this PR? This would be a useful change for us users.

**Comment by ninadingole** [comment]
What should be the name of the project in the OCA? Should I use "Oracle DB"?

**Comment by gvenzl** [comment]
Hi @ninadingole, please put "Golden Gate & Oracle DB" in there.

**Comment by ninadingole** [comment]
I have submitted the oca @gvenzl

**Comment by ninadingole** [comment]
@gvenzl can you let me know if my oca is accepted or not?

**Comment by gvenzl** [comment]
Hi @ninadingole,

Unfortunately I don't see your name yet listed as an accepted contributor.
I will see whether I can find our where we are at with this.
Sorry for the delay!

**Comment by gvenzl** [comment]
Good news, @ninadingole. Your OCA has been accepted and processed.

**Comment by nick-wagner** [comment]
This looks good.  The only thing I would suggest is changing the download location to http://edelivery.oracle.com/ because the FMW link may change soon.

**Comment by ninadingole** [comment]
@nick-wagner update the download location in the readme as well as update the scripts for new file pattern downloaded from edelivery.

**Comment by ninadingole** [comment]
@nick-wagner @gvenzl any updates on this? it's more than a year now 😢

**Comment by Djelibeybi** [comment]
@gvenzl I've removed @nick-wagner from the assignment as he is not a member of OGHO. Can we get another set of eyes on this?

**Comment by ninadingole** [comment]
can someone approves this if everything is good?

**Comment by javatarz** [comment]
Hey folks, this PR has been over 2 years in the making. Is there any way to speed up the paperwork and get this merged? As an individual contributor, it's nearly impossible to know the steps between where we are and where we need to be to get this merged. I believe all the steps mentioned in the [contribution guide](https://github.com/oracle/vagrant-projects/blob/master/CONTRIBUTING.md) have been met.

Can one of the maintainers please help make this a bit simpler to contribute to? I'm generally not a huge fan of doing calls but I think it might help to do one for this and to get the PR merged.

Is there a maintainer here who'd like to do this? @AmedeeBulle @gvenzl @ninadingole @Djelibeybi @totalamateurhour?

**Review by gvenzl — CHANGES_REQUESTED** [review]
@ninadingole, can you please rename the `19.1.0` directory to `19.3.0`. There never was a `19.1.0` release for on-premises installations, hence also the file name `LINUX.X64_193000_db_home.zip`.

Thanks,

**Comment by ninadingole** [comment]
@gvenzl done the changes, please let me know if anything else is needed :)

**Review by gvenzl — APPROVED** [review]
All good and ready to go!
Thank you so much for your contribution, @ninadingole!

**Pull request merged**
